function PwnMail() {
    Clear-Host

    $sleeping = $false
    Write-Host "PWNING UNLOCKED PC ..."

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host ""
    Write-Host "CREATING OUTLOOK APPLICATION OBJECT ..."

    if ($sleeping) { Start-Sleep 1.5 }

    $outlook = New-Object -ComObject Outlook.Application
    $namespace = $outlook.GetNamespace("MAPI")

    Write-Host $outlook

    Write-Host ""
    Write-Host "OUTLOOK APPLICATION OBJECT CREATED ..."

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host ""
    Write-Host "COMPOSING PWN EMAIL OBJECT ..."

    $mail = $outlook.CreateItem(0)

    $userEmail = $namespace.CurrentUser.AddressEntry.GetExchangeUser().PrimarySmtpAddress

    $recipient = $mail.Recipients.Add("hgraves@countyofcolusaca.gov")
    $mail.Recipients.Add($userEmail)
    $recipient.Type = 1

    $gifPath = "https://media1.tenor.com/m/kiv30bAOYtEAAAAd/gandalf-yes.gif"
    $cid = "gandalf.gif"

    $attachment = $mail.Attachments.Add($gifPath, 1, 0, "Woopsies!")
    $attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x3712001F", $cid)
    $attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x7D00000B", $true)



    $mail.Subject = "[PWN-MAIL] I left my PC unlocked and unattended!"
    $mail.HTMLBody = @"
<html>
<body>
Hi there!<br><br>Sorry about that! I'll do better so I don't get PWNED again. <br>
I'll read this article now:<br>
https://axionetworks.com/knowledge/cybersecurity-compliance/endpoint-security/why-you-should-always-lock-your-computer-when-you-step-away/
<br><br><br>
A message from the Purple Team:<br><br>
<i><b>Be more careful next time!<br>
<p><img src="cid:$cid" alt="Gandalf Yes" style="max-width: 400px;"/></p><br>
Your Friendly Neighborhood Purple Teamer,<br>
Cheers!<br></i></b>
<br>
<br>
<br><b>
-------------------------------------------------------------------------------<br>
THIS MESSAGE WAS GENERATED BY THE PWN-MAIL SCRIPT<br>
-------------------------------------------------------------------------------<br>
Details of the PWNED PC:<br></b>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User: $env:USERNAME<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Machine: $env:COMPUTERNAME<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Time: $(Get-Date)<br>
</body>
</html>
"@

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host $mail
    Write-Host ""
    Write-Host "PWN EMAIL OBJECT CREATED!"

    if ($sleeping) { Start-Sleep 1.5 }

    $mail.Display($false)
    $mail.send()

    Write-Host "PWN MAIL SENT!"
    Write-Host ""

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host "$userEmail, you got OWNED"
    Write-Host ""

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host "EXITING ..."

    if ($sleeping) { Start-Sleep 1.5 }

    Write-Host ""
    Write-Host ""
    Write-Host ""

    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($mail) | Out-Null
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($outlook) | Out-Null
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($namespace) | Out-Null

    Exit-PSHostProcess
}

function Main()
{
    PwnMail
}

Main
