Body: This is a test email sent from the spoofer script
Subject: Test Email from Spoofer Script
From: fakeemail@fakeorg.ca.gov
To: hgraves@countyofcolusaca.gov

Email Server: d326471b.ess.barracudanetworks.com
Port: 587